### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by AlberBhoi** [MBHudson/CryptoWalletCracker#1]
ENTER DELAY TIME IN SECONDS (ex: 20)
45 
Traceback (most recent call last):
  File "hash.py", line 6, in <module>
    from ellipticcurve.privateKey import PrivateKey
ModuleNotFoundError: No module named 'ellipticcurve'
1864919
No process found
1864920
No process found
1864921
No process found
1864922
No process found
1864923
Error: Process 1864923 detected, but you don't have permission to control it
No process found
1864924
No process found
1864925
No process found
1864926
No process found
No process found
1864927

**Comment by MBHudson** [comment]
Please try and run the following commands in sequentially. 

cd CryptoWalletCracker
sudo chmod +x install
sudo install
sudo cryptowalletcracker

**Comment by 3rr0r983** [comment]
i did what you said in the comment and i got 

/usr/bin/cryptowalletcracker: line 6: ./StageOne: No such file or directory
/usr/bin/cryptowalletcracker: line 8: ./StageTwo: No such file or directory

**Comment by MBHudson** [comment]
pip install ECPy
pip install elliptic-curve

**Comment by MBHudson** [comment]
cd
cd CryptoWalletCracker 
./CryptoWalletCracker

**Comment by 3rr0r983** [comment]
DEPRECATION: gpg 1.14.0-unknown has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of gpg or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: wfuzz 3.1.0 has a non-standard dependency specifier pyparsing>=2.4*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of wfuzz or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


this is strange
