### ISSUE TITLE
after execute first line commands

### ISSUE THREAD

**Issue by feiuz** [MBHudson/CryptoWalletCracker#3]
Archive:  00.zip
  inflating: 00.pickle               
Archive:  01.zip
  inflating: 01.pickle               
Archive:  02.zip
  inflating: 02.pickle               
Archive:  03.zip
  inflating: 03.pickle               
Archive:  04.zip
  inflating: 04.pickle               
Archive:  05.zip
  inflating: 05.pickle               
Archive:  06.zip
  inflating: 06.pickle               
Archive:  07.zip
  inflating: 07.pickle               
Archive:  08.zip
  inflating: 08.pickle               
Archive:  09.zip
  inflating: 09.pickle               
Archive:  10.zip
  inflating: 10.pickle               
Archive:  11.zip
  inflating: 11.pickle               
Archive:  12.zip
  inflating: 12.pickle               
Archive:  13.zip
  inflating: 13.pickle               
Archive:  14.zip
  inflating: 14.pickle               
Archive:  15.zip
  inflating: 15.pickle               
Archive:  16.zip
  inflating: 16.pickle               
Archive:  17.zip
  inflating: 17.pickle               
Archive:  18.zip
  inflating: 18.pickle               
Archive:  19.zip
  inflating: 19.pickle               
rm: cannot remove '*.zip': No such file or directory
./cryptowalletcracker: line 3: cd: CryptoWalletCracker: No such file or directory
ENTER DELAY TIME IN SECONDS (ex: 20)
20
./cryptowalletcracker: line 6: ./StageOne: No such file or directory
./cryptowalletcracker: line 8: ./StageTwo: No such file or directory

**Comment by MBHudson** [comment]
sudo ./install

**Comment by MBHudson** [comment]
.

**Comment by MBHudson** [comment]
.

**Comment by MBHudson** [comment]
sudo rm *.zip

**Comment by MBHudson** [comment]
Just unzip everything and them delete the .zip files in the same path they were downloaded to
